name: vania
description: Fast, simple, and powerful backend framework for Dart built with
version: 0.3.2
homepage: https://vdart.dev
repository: https://github.com/vania-dart/framework
issue_tracker: https://github.com/vania-dart/framework/issues
documentation: https://vdart.dev/docs/intro
topics: [server, backend, httpserver, framework, web]

screenshots:
  - description: 'Vania web application'
    path: assets/logo.png

environment:
   sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.14.0
  eloquent: ^3.2.1
  mailer: ^6.1.0
  meta: ^1.15.0
  mime: ^1.0.5
  path: ^1.9.0
  sprintf: ^7.0.0
  string_scanner: ^1.2.0
  uuid: ^4.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.5
  http: ^1.2.1
  http_parser: ^4.0.2
